const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
const source=fs.readFileSync(require('node:path').join(__dirname,'../index.html'),'utf8').match(/<script>([\s\S]*?)<\/script>/)[1];
function engine(){const c=vm.createContext({});vm.runInContext(source+';state=initial();',c);return x=>vm.runInContext(x,c)}
test('six nations start with provinces and reciprocal hex adjacency',()=>{const run=engine();assert.equal(run('NATIONS.every((_,i)=>owned(state,i).length>0)'),true);assert.equal(run('state.tiles.every(t=>neighbors(t.id).every(n=>neighbors(n).includes(t.id)))'),true)});
test('movement requires adjacency and war, and arrives after two weeks',()=>{const r=engine();assert.equal(r('send(9,47,0)'),false);assert.equal(r('send(2,3,0)'),false);r('state.wars[1]=true;state.tiles[2].troops=100;state.tiles[3].troops=1');assert.equal(r('send(2,3,0)'),true);r('tick()');assert.equal(r('state.tiles[3].owner'),1);r('tick()');assert.equal(r('state.tiles[3].owner'),0)});
test('peace recalls pending hostile army without conquest',()=>{const r=engine();r('state.wars[1]=true;state.tiles[2].troops=100;send(2,3,0);state.wars[1]=false;tick();tick()');assert.equal(r('state.tiles[3].owner'),1);assert.equal(r('state.tiles[2].troops'),100)});
test('research completes and economy produces finite values',()=>{const r=engine();r('state.research={left:10};for(let i=0;i<10;i++)tick()');assert.equal(r('state.tech'),2);assert.equal(r('state.research'),null);assert.equal(r('Number.isFinite(state.cash)'),true)});
test('victory, defeat, and unrest collapse resolve',()=>{let r=engine();r('state.tiles.slice(0,24).forEach(t=>t.owner=0);tick()');assert.match(r('state.outcome'),/Victory/);r=engine();r('state.tiles.forEach(t=>t.owner=1);tick()');assert.match(r('state.outcome'),/Defeat/);r=engine();r('state.approval=0;state.tax=50;state.welfare=0;state.wars.fill(true);for(let i=0;i<12;i++)tick()');assert.match(r('state.outcome'),/collapsed/)});
test('valid saves roundtrip and corrupt saves fail',()=>{const r=engine();assert.equal(r('validSave(JSON.parse(JSON.stringify(state)))'),true);assert.equal(r('validSave({version:1})'),false);r('state.tiles[0].owner=88');assert.equal(r('validSave(state)'),false)});
test('long simulation preserves nonnegative troops and finite treasury',()=>{const r=engine();r('for(let i=0;i<250;i++)tick()');assert.equal(r('state.tiles.every(t=>t.troops>=0)&&Number.isFinite(state.cash)'),true)});
