const {test}=require('node:test');const assert=require('node:assert/strict');const G=require('../src/engine.js');
function quiet(s){s.divisions.filter(d=>d.owner!==0).forEach(d=>d.org=0)}
test('all nations have valid capitals, connected provinces, and symmetric adjacency',()=>{const s=G.initial();assert.equal(G.valid(s),true);G.nations.forEach((n,i)=>{assert.equal(G.province(s,n.capital).owner,i);assert.equal(Object.keys(G.supply(s,i)).length,G.land(s,i).length)});G.map.forEach(p=>G.adjacent(p.id).forEach(id=>assert(G.adjacent(id).includes(p.id))))});
test('orders reject nonadjacency and neutral territory',()=>{const s=G.initial(),d=s.divisions.find(d=>d.owner===0);assert.match(G.command(s,'order',{id:d.id,target:57}),/neighboring/);d.loc=26;assert.match(G.command(s,'order',{id:d.id,target:14}),/closed/)});
test('movement takes days and cannot teleport',()=>{const s=G.initial();quiet(s);const d=s.divisions.find(d=>d.owner===0);d.loc=26;G.command(s,'order',{id:d.id,target:27});G.step(s);assert.equal(d.loc,26);G.step(s);assert.equal(d.loc,27);assert.equal(d.order,null)});
test('sustained combat damages defenders before a capture',()=>{const s=G.initial();const d=s.divisions.find(d=>d.owner===0);d.loc=29;const enemy=s.divisions.find(d=>d.owner===1);enemy.loc=30;enemy.org=40;s.divisions=s.divisions.filter(x=>x.id===d.id||x.id===enemy.id);G.command(s,'order',{id:d.id,target:30});G.step(s);assert(enemy.org<40);assert.equal(G.province(s,30).owner,1);assert(d.strength<100);assert(G.valid(s))});
test('encirclement cuts supply and causes attrition',()=>{const s=G.initial();s.divisions=s.divisions.filter(d=>d.owner===0);const d=s.divisions[0];d.loc=41;G.adjacent(41).forEach(id=>G.province(s,id).owner=1);assert.equal(G.supplyLevel(s,d),.15);G.step(s);assert(d.strength<100)});
test('production allocates all active factories and equipment funds training',()=>{const s=G.initial();G.command(s,'allocation',{value:6});assert.equal(G.rates(s).tanks,0);assert.equal(G.rates(s).rifles,72);const rifles=s.rifles,mp=s.manpower;G.command(s,'recruit',{type:'infantry'});assert.equal(s.rifles,rifles-300);assert.equal(s.manpower,mp-5000);quiet(s);const count=s.divisions.filter(d=>d.owner===0).length;for(let i=0;i<10;i++)G.step(s);assert.equal(s.divisions.filter(d=>d.owner===0).length,count+1);assert.equal(s.recruit.length,0)});
test('armor requires fuel and cannot move when the pool is exhausted',()=>{const s=G.initial(),d=s.divisions.find(d=>d.owner===0&&d.type==='armor');d.loc=26;s.fuel=0;assert.match(G.command(s,'order',{id:d.id,target:27}),/fuel/)});
test('research, national focus, and construction complete on schedule',()=>{const s=G.initial();s.war.fill(false);assert.match(G.command(s,'focus',{id:'arsenal'}),/not available/);G.command(s,'focus',{id:'mobilize'});G.command(s,'research',{kind:'weapons'});G.command(s,'build',{id:26,kind:'factory'});for(let i=0;i<28;i++)G.step(s);assert(s.completed.includes('mobilize'));assert.equal(s.tech.weapons,1);assert.equal(s.mil,7);assert.equal(s.construction,null);assert.equal(s.focus,null)});
test('ceasefires cancel incoming hostile orders and preserve borders',()=>{const s=G.initial();s.political=100;G.command(s,'order',{id:0,target:30});G.command(s,'peace',{n:1});assert.equal(s.war[1],false);assert.equal(s.divisions[0].order,null);for(let i=0;i<5;i++)G.step(s);assert.equal(G.province(s,30).owner,1)});
test('fuel trade and alliance enforce cost and relations',()=>{const s=G.initial();assert.match(G.command(s,'trade',{n:2}),/requires/);G.command(s,'improve',{n:2});const pp=s.political;G.command(s,'trade',{n:2});assert.equal(s.political,pp-25);assert.equal(s.trade[2],true);assert.equal(G.rates(s).fuel,16);assert.match(G.command(s,'alliance',{n:2}),/requires/)});
test('capital loss ends campaign; Karsk capitulates after sufficient territorial loss',()=>{let s=G.initial();G.province(s,26).owner=1;G.step(s);assert.match(s.outcome,/Defeat/);s=G.initial();s.war.fill(false);s.divisions=s.divisions.filter(d=>d.owner!==1);const k=G.land(s,1);k.slice(0,8).forEach(p=>p.owner=0);G.province(s,32).owner=0;G.step(s);assert.match(s.outcome,/Victory/);assert.equal(G.land(s,1).length,0);const day=s.day;G.step(s);assert.equal(s.day,day)});
test('battle-plan assignment advances armies and long simulations remain valid',()=>{const s=G.initial();G.command(s,'plan');G.command(s,'execute');for(let i=0;i<180;i++){G.step(s);assert(G.valid(s),'invalid on day '+s.day)}assert(s.day>1);assert(s.outcome);assert(s.log.some(e=>/captured/.test(e.text)))});
test('save roundtrip restores canonical map and rejects invalid data',()=>{const s=G.initial();const raw=JSON.parse(JSON.stringify(s));raw.provinces[0].name='<script>';const restored=G.restore(raw);assert.equal(restored.provinces[0].name,G.map[0].name);assert(G.valid(restored));raw.divisions[0].order=999;assert.throws(()=>G.restore(raw));assert.equal(G.valid({version:1}),false)});
