/* Sovereign World: Iron Dawn. Deterministic, dependency-free campaign simulation. */
(function(root){
'use strict';
const nations=[{name:'Aster Republic',short:'ASTER',color:'#739393',capital:26,ideology:'Parliamentary republic'},{name:'Karsk Directorate',short:'KARSK',color:'#a6856f',capital:32,ideology:'Military authoritarianism'},{name:'Veyran League',short:'VEYRA',color:'#8b92a4',capital:6,ideology:'Federal democracy'},{name:'Solarian Commonwealth',short:'SOLARA',color:'#b6a379',capital:75,ideology:'Constitutional monarchy'},{name:'Meridian Union',short:'MERIDIAN',color:'#8c9b76',capital:78,ideology:'Socialist republic'},{name:'Kingdom of Orinth',short:'ORINTH',color:'#9e8593',capital:57,ideology:'Constitutional monarchy'}];
const mask=['...######...','..########..','.##########.','############','############','.###########','..#########.','...#######..'];
const terrain=['Plains','Forest','Hills','Mountains'];
const cityNames={6:'Velgrad',26:'Asterhaven',32:'Karsk City',75:'Solhaven',78:'Meridia',57:'Orin',29:'Brenner',40:'Eisenfeld',43:'Nordvik',51:'Greybridge',65:'Saltport',76:'Highpass'};
const focuses=[{id:'mobilize',name:'Emergency Mobilization',desc:'+18,000 manpower. Opens the war cabinet.',days:14,parent:null},{id:'arsenal',name:'Arsenal of the Republic',desc:'+2 military factories.',days:21,parent:'mobilize'},{id:'logistics',name:'Army Logistics Bureau',desc:'Supply reach +3 provinces.',days:21,parent:'mobilize'},{id:'resolve',name:'A Nation United',desc:'+15 stability and +15 war support.',days:14,parent:'mobilize'},{id:'armor',name:'Armored Spearhead',desc:'+40 tanks and +20% armor attack.',days:28,parent:'arsenal'}];
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function vertex(c,r){return [90+c*77+Math.sin(r*.8)*20+Math.sin(c*11+r*5)*12,65+r*70+Math.sin(c*.8)*15+Math.cos(c*7+r*9)*10]}
function edge(a,b){const reverse=a[0]>b[0]||(a[0]===b[0]&&a[1]>b[1]);if(reverse)return edge(b,a).reverse();const dx=b[0]-a[0],dy=b[1]-a[1],len=Math.hypot(dx,dy),key=a[0]*.13+a[1]*.17;return Array.from({length:7},(_,i)=>{const t=i/6,w=i===0||i===6?0:Math.sin(key+i*2.7)*8;return [a[0]+dx*t-dy/len*w,a[1]+dy*t+dx/len*w]})}
function makeMap(){let out=[];for(let r=0;r<8;r++)for(let c=0;c<12;c++){if(mask[r][c]!== '#')continue;const id=r*12+c;const owner=r<2?2:r>=6?(c<6?3:4):c>=9?5:c<6?0:1;const corners=[vertex(c,r),vertex(c+1,r),vertex(c+1,r+1),vertex(c,r+1)];const edges=corners.map((p,i)=>edge(p,corners[(i+1)%4]));const poly=edges.flatMap(e=>e.slice(0,-1));out.push({id,r,c,owner,home:owner,name:cityNames[id]||['West','North','Upper','Lower','East','South'][id%6]+['moor','haven','wald','ridge','feld','brook','vale'][Math.floor(id/6)%7],terrain:(c===6&&r>2)?3:(id*7+3)%11<3?1:(id*3)%9<2?2:0,city:!!cityNames[id],vp:cityNames[id]?5:1,infra:cityNames[id]?3:2,fort:0,poly,edges,x:corners.reduce((s,p)=>s+p[0],0)/4,y:corners.reduce((s,p)=>s+p[1],0)/4});}return out}
const map=makeMap();const ids=new Set(map.map(p=>p.id));
function adjacent(id){const r=Math.floor(id/12),c=id%12;return [[r,c-1],[r,c+1],[r-1,c],[r+1,c]].filter(([y,x])=>y>=0&&y<8&&x>=0&&x<12&&ids.has(y*12+x)).map(([y,x])=>y*12+x)}
function province(s,id){return s.provinces.find(p=>p.id===id)}
function land(s,n=0){return s.provinces.filter(p=>p.owner===n)}
function entry(s,text){s.log.unshift({day:s.day,text});s.log=s.log.slice(0,35)}
function newDivision(s,owner,loc,type='infantry'){const id=s.nextId++;return {id,owner,loc,type,name:(id+1)+(type==='armor'?' Armored':' Infantry'),strength:100,org:100,order:null,progress:0,plan:false}}
function initial(){const s={version:2,day:0,provinces:map.map(p=>({...p})),divisions:[],nextId:0,manpower:42000,rifles:1250,tanks:90,fuel:640,political:70,stability:68,support:72,mil:6,civ:4,allocation:4,recruit:[],construction:null,research:null,tech:{weapons:0,industry:0},focus:null,completed:[],relations:[100,-80,25,10,5,20],war:[false,true,false,false,false,false],trade:[false,false,false,false,false,false],alliance:[false,false,false,false,false,false],capitulated:[false,false,false,false,false,false],offensive:false,log:[{day:0,text:'3 September 1939. Karsk has crossed the Brenner frontier. The Republic mobilizes.'}],outcome:null};
for(let n=0;n<6;n++){let tiles=land(s,n);let positions=n===0?[29,41,53,65,28,40,52,64]:n===1?[30,42,54,66,31,43,55,67]:tiles.filter(p=>p.city).map(p=>p.id).concat(tiles.slice(0,2).map(p=>p.id));positions.forEach((loc,i)=>{if(province(s,loc)?.owner===n)s.divisions.push(newDivision(s,n,loc,i===3?'armor':'infantry'))})}return s}
function supply(s,n=0){const capital=nations[n].capital,start=province(s,capital);const distances={};if(start?.owner!==n)return distances;const queue=[capital];distances[capital]=0;for(let i=0;i<queue.length;i++){const id=queue[i];for(const next of adjacent(id))if(distances[next]===undefined&&province(s,next).owner===n){distances[next]=distances[id]+1;queue.push(next)}}return distances}
function supplyLevel(s,d,cache){const dist=(cache||supply(s,d.owner))[d.loc];if(dist===undefined)return .15;const reach=6+(d.owner===0&&s.completed.includes('logistics')?3:0);return clamp(1-Math.max(0,dist-reach)*.14,.3,1)}
function factories(s){const ratio=land(s).length/map.filter(p=>p.home===0).length;return Math.max(0,Math.floor(s.mil*Math.min(1,ratio)))}
function rates(s){const f=factories(s),rifle=Math.min(s.allocation,f),bonus=1+s.tech.industry*.2;return {rifles:Math.round(rifle*12*bonus),tanks:Math.round((f-rifle)*2*bonus),fuel:8+s.trade.filter(Boolean).length*8}}
function checkOrder(s,d,target){if(!d||d.owner!==0)return 'Select one of your divisions first.';if(!adjacent(d.loc).includes(target))return 'Divisions move one neighboring province at a time.';const p=province(s,target);if(p.owner!==0&&!s.war[p.owner])return 'That border is closed. Declare war in Diplomacy first.';if(d.org<15)return 'This division needs at least 15 organization to advance.';if(d.type==='armor'&&s.fuel<5)return 'Armored divisions need fuel.';return null}
function command(s,action,args={}){if(s.outcome)return 'The campaign has ended. Start a new campaign to continue.';const fail=msg=>msg;
if(action==='order'){const d=s.divisions.find(d=>d.id===args.id);const err=checkOrder(s,d,args.target);if(err)return err;d.order=args.target;d.progress=0;d.plan=false;return 'Orders issued. Advance begins when time runs.'}
if(action==='halt'){const d=s.divisions.find(d=>d.id===args.id&&d.owner===0);if(!d)return fail('Select a division.');d.order=null;d.plan=false;d.progress=0;return 'Division ordered to hold.'}
if(action==='plan'){s.divisions.filter(d=>d.owner===0).forEach(d=>d.plan=true);return 'All divisions assigned to the Eastern Army battle plan.'}
if(action==='execute'){s.offensive=!s.offensive;if(!s.offensive)s.divisions.filter(d=>d.owner===0&&d.plan).forEach(d=>{d.order=null;d.progress=0});return s.offensive?'Battle plan executing. Assigned divisions will seek and attack hostile borders.':'Battle plan halted.'}
if(action==='recruit'){const armor=args.type==='armor',cost=armor?{mp:2400,r:150,t:40,d:16}:{mp:5000,r:300,t:0,d:10};if(s.recruit.length>=4)return fail('Training queue is full (4 divisions).');if(s.manpower<cost.mp||s.rifles<cost.r||s.tanks<cost.t)return fail('Not enough manpower or equipment.');s.manpower-=cost.mp;s.rifles-=cost.r;s.tanks-=cost.t;s.recruit.push({type:armor?'armor':'infantry',left:cost.d,total:cost.d});return 'Division training started. Equipment and manpower reserved.'}
if(action==='allocation'){s.allocation=clamp(Math.round(Number(args.value)||0),0,factories(s));return 'Factory allocation updated.'}
if(action==='build'){if(s.construction)return fail('A construction project is already active.');const p=province(s,args.id);if(!p||p.owner!==0)return fail('Select a province you control.');if(args.kind!=='factory'&&args.kind!=='fort')return fail('Unknown construction project.');if(args.kind==='fort'&&p.fort>=3)return fail('Fortifications are already at maximum level.');s.construction={id:p.id,kind:args.kind,left:args.kind==='factory'?28:10,total:args.kind==='factory'?28:10};return 'Civilian factories assigned to construction.'}
if(action==='research'){if(s.research)return fail('A research project is already active.');if(!['weapons','industry'].includes(args.kind)||s.tech[args.kind]>=3)return fail('This technology is fully researched.');s.research={kind:args.kind,left:24,total:24};return 'Research started. Completion in 24 days.'}
if(action==='focus'){const f=focuses.find(f=>f.id===args.id);if(!f||s.focus||s.completed.includes(f.id)||(f.parent&&!s.completed.includes(f.parent)))return fail('This focus is not available yet.');s.focus={id:f.id,left:f.days,total:f.days};return 'National focus selected: '+f.name+'.'}
if(action==='mobilize'){if(s.political<60)return fail('Requires 60 political power.');if(s.manpower>=100000)return fail('Manpower reserve is already sufficient.');s.political-=60;s.manpower+=15000;s.stability=clamp(s.stability-8,0,100);return 'Conscription expanded: +15,000 manpower, −8 stability.'}
if(['improve','trade','alliance','war','peace'].includes(action)){const n=args.n;if(!Number.isInteger(n)||n<1||n>5||s.capitulated[n])return fail('No active diplomatic partner selected.');if(action==='war'){if(s.war[n])return fail('Already at war.');s.war[n]=true;s.alliance[n]=false;s.trade[n]=false;s.relations[n]=-80;s.stability=clamp(s.stability-5,0,100);entry(s,'War declared on '+nations[n].name+'.');return 'War declared.'}if(action==='peace'){if(!s.war[n])return fail('You are not at war.');if(s.political<90)return fail('A ceasefire requires 90 political power.');s.political-=90;s.war[n]=false;s.relations[n]=0;s.divisions.forEach(d=>{if(d.order!==null&&((d.owner===0&&province(s,d.order).owner===n)||(d.owner===n&&province(s,d.order).owner===0))){d.order=null;d.progress=0}});entry(s,'Ceasefire signed with '+nations[n].name+'.');return 'Ceasefire signed. Current borders remain.'}if(s.war[n])return fail('Negotiate peace before diplomacy.');if(action==='improve'){if(s.political<20)return fail('Requires 20 political power.');s.political-=20;s.relations[n]=clamp(s.relations[n]+20,-100,100);return 'Relations improved by 20.'}if(action==='trade'){if(s.trade[n]||s.relations[n]<30||s.political<25)return fail('Trade requires 30 relations and 25 political power.');s.political-=25;s.trade[n]=true;return 'Fuel agreement signed: +8 fuel per day.'}if(action==='alliance'){if(s.alliance[n]||s.relations[n]<70||s.political<50)return fail('Alliance requires 70 relations and 50 political power.');s.political-=50;s.alliance[n]=true;entry(s,nations[n].name+' joins the Republican Accord.');return 'Alliance signed. Allied nations remain nonbelligerent in this prototype.'}}
return fail('Unknown command.')}
function routeToFront(s,d){const queue=[{id:d.loc,first:null}],seen=new Set([d.loc]);for(let i=0;i<queue.length;i++){const {id,first}=queue[i];for(const n of adjacent(id)){const p=province(s,n),hostile=d.owner===0?s.war[p.owner]:p.owner===0&&s.war[d.owner];if(hostile)return first??n;if(p.owner===d.owner&&!seen.has(n)){seen.add(n);queue.push({id:n,first:first??n})}}}return null}
function hostile(s,a,b){return a!==b&&((a===0&&s.war[b])||(b===0&&s.war[a]))}
function power(s,d,attack){let v=(d.type==='armor'?14:9)*(d.strength/100)*(.35+.65*d.org/100)*supplyLevel(s,d);if(d.owner===0)v*=1+s.tech.weapons*.15;if(d.type==='armor'&&d.owner===0){if(s.fuel<5)v*=.3;if(s.completed.includes('armor'))v*=1.2}if(!attack){const p=province(s,d.loc);v*=1+[0,.15,.25,.55][p.terrain]+p.fort*.2}return v}
function retreat(s,d){const p=adjacent(d.loc).map(id=>province(s,id)).find(p=>p.owner===d.owner&&!s.divisions.some(x=>x.order===p.id&&hostile(s,d.owner,x.owner)));if(p){d.loc=p.id;d.order=null;d.progress=0;d.org=18}else{d.strength=0;entry(s,nations[d.owner].short+' division encircled and destroyed.')}}
function step(s){if(s.outcome)return;s.day++;const r=rates(s);s.rifles+=r.rifles;s.tanks+=r.tanks;s.fuel=Math.min(1500,s.fuel+r.fuel);s.political+=2;s.manpower+=Math.round(35*s.stability/100);const caches=Array.from({length:6},(_,n)=>supply(s,n));
for(const d of s.divisions){const sup=supplyLevel(s,d,caches[d.owner]);const fighting=d.order!==null&&hostile(s,d.owner,province(s,d.order).owner)||s.divisions.some(x=>x.order===d.loc&&hostile(s,x.owner,d.owner));if(!fighting)d.org=clamp(d.org+6*sup,0,100);if(sup<.3){d.strength-=1.3;d.org=Math.max(0,d.org-4)}else if(!fighting&&d.strength<100){if(d.owner===0&&s.rifles>=5&&s.manpower>=40){s.rifles-=5;s.manpower-=40;d.strength=Math.min(100,d.strength+2)}else if(d.owner!==0)d.strength=Math.min(100,d.strength+1)}if(d.order===null&&d.org>45&&((d.owner===0&&d.plan&&s.offensive)||(d.owner!==0&&s.war[d.owner]))){d.order=routeToFront(s,d);d.progress=0}}
// Resolve a target as a combined battle, so multiple attacking divisions cooperate.
const targets=[...new Set(s.divisions.filter(d=>d.order!==null).map(d=>d.order))];for(const target of targets){let attackers=s.divisions.filter(d=>d.order===target&&d.strength>0);if(!attackers.length)continue;const p=province(s,target);const owner=attackers[0].owner;attackers=attackers.filter(d=>d.owner===owner);if(p.owner!==owner&&!hostile(s,owner,p.owner)){attackers.forEach(d=>d.order=null);continue}attackers=attackers.filter(d=>{if(d.type==='armor'&&d.owner===0){if(s.fuel<5)return false;s.fuel-=5}return true});if(!attackers.length)continue;let defenders=s.divisions.filter(d=>d.loc===target&&d.owner===p.owner&&d.owner!==owner&&d.strength>0);if(defenders.length){const a=attackers.reduce((sum,d)=>sum+power(s,d,true),0),b=defenders.reduce((sum,d)=>sum+power(s,d,false),0);defenders.forEach(d=>{d.org-=a/defenders.length*1.1;d.strength-=a/defenders.length*.25;if(d.org<=8&&d.strength>0)retreat(s,d)});attackers.forEach(d=>{d.org-=b/attackers.length*.8+1;d.strength-=b/attackers.length*.2;if(d.org<=10){d.order=null;d.progress=0}});defenders=s.divisions.filter(d=>d.loc===target&&d.owner===p.owner&&d.owner!==owner&&d.strength>0);if(defenders.length)continue}
attackers.filter(d=>d.order===target&&d.strength>0).forEach(d=>{d.progress+=1;const needed=p.terrain===3?4:d.type==='armor'?1:2;if(d.progress>=needed){if(p.owner!==owner){p.owner=owner;if(p.city)entry(s,nations[owner].short+' captured '+p.name+'.')}d.loc=target;d.order=null;d.progress=0;d.org=Math.max(10,d.org-5)}})}
s.divisions.forEach(d=>{d.org=clamp(d.org,0,100);d.strength=clamp(d.strength,0,100)});s.divisions=s.divisions.filter(d=>d.strength>0);
for(const q of s.recruit)q.left--;const capital=province(s,nations[0].capital);if(capital?.owner===0){s.recruit.filter(q=>q.left<=0).forEach(q=>{s.divisions.push(newDivision(s,0,capital.id,q.type));entry(s,'A new '+q.type+' division deployed at '+capital.name+'.')});s.recruit=s.recruit.filter(q=>q.left>0)}
if(s.construction){const q=s.construction,p=province(s,q.id);if(p.owner!==0){entry(s,'Construction abandoned after the province was lost.');s.construction=null}else if(--q.left<=0){if(q.kind==='factory')s.mil++;else p.fort++;entry(s,q.kind==='factory'?'New military factory commissioned.':'Fortifications completed at '+p.name+'.');s.construction=null}}
if(s.research&&--s.research.left<=0){s.tech[s.research.kind]++;entry(s,'Research complete: '+s.research.kind+'.');s.research=null}
if(s.focus&&--s.focus.left<=0){const id=s.focus.id;s.completed.push(id);if(id==='mobilize')s.manpower+=18000;if(id==='arsenal')s.mil+=2;if(id==='resolve'){s.stability=clamp(s.stability+15,0,100);s.support=clamp(s.support+15,0,100)}if(id==='armor')s.tanks+=40;entry(s,'National focus complete: '+focuses.find(f=>f.id===id).name+'.');s.focus=null}
if(s.day%16===0){for(let n=1;n<6;n++)if(!s.capitulated[n]&&s.war[n]&&s.divisions.filter(d=>d.owner===n).length<14&&province(s,nations[n].capital)?.owner===n)s.divisions.push(newDivision(s,n,nations[n].capital,s.day%48===0?'armor':'infantry'))}
for(let n=1;n<6;n++){if(s.capitulated[n])continue;const original=map.filter(p=>p.home===n),held=original.filter(p=>province(s,p.id).owner===n);const lostCapital=province(s,nations[n].capital)?.owner!==n;if(lostCapital&&held.length/original.length<.5){s.capitulated[n]=true;s.war[n]=false;s.trade[n]=false;s.alliance[n]=false;land(s,n).forEach(p=>p.owner=0);s.divisions=s.divisions.filter(d=>d.owner!==n);entry(s,nations[n].name+' capitulated. Remaining territory surrendered.')}}
if(capital.owner!==0||!land(s).length)s.outcome='Defeat — Asterhaven has fallen.';else if(s.capitulated[1])s.outcome='Victory — the Karsk Directorate has capitulated.';if(s.outcome)entry(s,s.outcome)}
function valid(s){try{return !!s&&s.version===2&&Number.isInteger(s.day)&&s.day>=0&&s.provinces.length===map.length&&s.provinces.every((p,i)=>p.id===map[i].id&&Number.isInteger(p.owner)&&p.owner>=0&&p.owner<6&&Number.isInteger(p.fort)&&p.fort>=0&&p.fort<=3)&&['manpower','rifles','tanks','fuel','political','stability','support','mil','civ','allocation','nextId'].every(k=>Number.isFinite(s[k])&&s[k]>=0)&&Array.isArray(s.divisions)&&s.divisions.every(d=>Number.isInteger(d.id)&&d.id>=0&&Number.isInteger(d.owner)&&d.owner>=0&&d.owner<6&&ids.has(d.loc)&&['infantry','armor'].includes(d.type)&&Number.isFinite(d.strength)&&d.strength>0&&d.strength<=100&&Number.isFinite(d.org)&&d.org>=0&&d.org<=100&&(d.order===null||adjacent(d.loc).includes(d.order))&&Number.isFinite(d.progress)&&d.progress>=0&&typeof d.plan==='boolean')&&new Set(s.divisions.map(d=>d.id)).size===s.divisions.length&&s.divisions.every(d=>d.id<s.nextId)&&['war','trade','alliance','capitulated'].every(k=>s[k].length===6&&s[k].every(v=>typeof v==='boolean'))&&s.relations.length===6&&s.relations.every(Number.isFinite)&&['weapons','industry'].every(k=>Number.isInteger(s.tech[k])&&s.tech[k]>=0&&s.tech[k]<=3)&&Array.isArray(s.completed)&&s.completed.every(id=>focuses.some(f=>f.id===id))&&Array.isArray(s.recruit)&&s.recruit.length<=4&&s.recruit.every(q=>['armor','infantry'].includes(q.type)&&Number.isFinite(q.left)&&Number.isFinite(q.total)&&q.total>0)&&(s.construction===null||(ids.has(s.construction.id)&&['factory','fort'].includes(s.construction.kind)&&s.construction.left>0&&s.construction.total>0))&&(s.research===null||(['weapons','industry'].includes(s.research.kind)&&s.research.left>0&&s.research.total>0))&&(s.focus===null||(focuses.some(f=>f.id===s.focus.id)&&s.focus.left>0&&s.focus.total>0))&&typeof s.offensive==='boolean'&&(s.outcome===null||typeof s.outcome==='string')&&s.log.length<=35&&s.log.every(e=>Number.isInteger(e.day)&&typeof e.text==='string')}catch{return false}}
function restore(s){if(!valid(s))throw Error('Invalid save');const result=JSON.parse(JSON.stringify(s));result.provinces=map.map((p,i)=>({...p,owner:s.provinces[i].owner,fort:s.provinces[i].fort}));result.divisions.forEach(d=>d.name=(d.id+1)+(d.type==='armor'?' Armored':' Infantry'));return result}
const api={nations,focuses,terrain,map,adjacent,province,land,supply,supplyLevel,factories,rates,initial,command,step,valid,restore};if(typeof module!=='undefined')module.exports=api;else root.Game=api;
})(globalThis);
